name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v1
    - name: Git Leaks
      uses: GiriRaj249/gitleaks-action@v1
      with:
        token: ${{ secrets.GIT_ACTION_TOKEN }}
