name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v1
    - name: Git Leaks
      uses: actions/checkout@v2
      with:
        repository: GiriRaj249/gitleaks-action
        ref: v1
        token: ${{ secrets.GIT_ACTION_TOKEN }}
