name: gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Git Leaks
      uses: actions/checkout@v2
      with:
        repository: GiriRaj249/gitleaks-action@main
        token: ${{ secrets.GIT_ACTION_TOKEN }}
