name: gitleaks

on: [push, pull_request, workflow_dispatch]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gitleaks-action with config
        uses: actions/checkout@v2
        with:
          repository: GiriRaj249/gitleaks-action
          ref: main
          path: ./action
      - name: run git actions
        uses: ./action
